name: flutter_fit_events
description: "A flutter package that handles listening and publishing events throughout your app."
version: 1.0.0
homepage: https://pub.dev/packages/flutter_fit_events
repository: https://github.com/vaistudio/flutter_fit_events
issue_tracker: https://github.com/vaistudio/flutter_fit_events/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - events
  - dispatcher
  - observer

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
